name: build
run-name: ${{ github.actor }} is building
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: Dist
          path: dist/
